### ISSUE TITLE
numpy casting error for .take

### ISSUE THREAD

**Issue by dineshbvadhia** [Philip-Bachman/NN-Python#4]
The following error occurs on Windows 8.1 and Ubuntu 11.04 both running 32-bit Python (Anaconda 2.1).

> \NN-Python\nlp>python nlmodels.py

PROGRESS: at sentence #0, processed 0 words and 0 word types collected 446 word types from a corpus of 838 words and 7 sentences total 49 word types after removing those with count<3
Training all parameters:
Traceback (most recent call last):
  File "nlmodels.py", line 752, in <module>
    test_pv_model()
  File "nlmodels.py", line 699, in test_pv_model
    train_ctx=True, train_lut=True, train_cls=True, learn_rate=1e-3)
  File "nlmodels.py", line 152, in train
    post_code_keys = hsm_code_keys.take(post_keys,axis=0)
TypeError: Cannot cast array data from dtype('uint32') to dtype('int32') according to the rule 'safe'

Haven't tested it on 64-bit Python. It is possible that it is a numpy bug and have posted the error on the numpy mailing list.

Changing to:

```
post_code_keys = hsm_code_keys[post_keys]
```

works and is my preferred method over ".take" and is just as fast. The NN-Python/nlp code runs fine with all ".take" instances replaced as above.

**Comment by dineshbvadhia** [comment]
Posted issue on numpy discussion list and it does appear to be a problem on 32-bit OS's. No resolution yet. In meantime, will be safer to use advanced indexing method (as shown above).

**Comment by dineshbvadhia** [comment]
There was no resolution on the numpy list except that it seems to effect 32-bit systems. As I'm now using 64-bit OS's, this issue can be closed.
